import React, { useState, useEffect } from 'react';
import StatusModal from '../components/StatusModal';
import RecruitmentModal, { type RecruitmentRequest } from '../components/RecruitmentModal';
import Loading from '../components/Loading';
import TopBar from '../components/TopBar';
import Sidebar from '../components/Sidebar';
import '../styles/App.css';
import '../styles/index.css';
import '../styles/StatusModal.css';

const Recruitment: React.FC = () => {
  const [requests, setRequests] = useState<RecruitmentRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [selectedRequest, setSelectedRequest] = useState<RecruitmentRequest | null>(null);
  const [theme, setTheme] = useState(localStorage.getItem('hrapp.theme') || 'light');
  const [statusModal, setStatusModal] = useState({ open: false, success: false, message: '' });

  useEffect(() => {
    document.documentElement.classList.remove('theme-light', 'theme-dark');
    document.documentElement.classList.add(`theme-${theme}`);
    localStorage.setItem('hrapp.theme', theme);
  }, [theme]);

  useEffect(() => {
    const fetchRequests = async () => {
      setLoading(true);
      setError(null);
      try {
        const url = `${import.meta.env.VITE_API_BASE_URL}/recruitment`;
        const res = await fetch(url, {
          headers: { 'x-api-key': import.meta.env.VITE_API_KEY },
        });
        if (!res.ok) throw new Error('Failed to fetch recruitment requests');
        const data = await res.json();
        interface RecruitmentApi {
          RecruitmentId: number;
          RecruitmentDate: string;
          FirstName: string;
          MiddleName: string;
          LastName: string;
          Phone: string;
          Email: string;
          Position: string;
          Status: string;
          Notes?: string;
          CreatedAt?: string;
        }
        const mapped = (data as RecruitmentApi[]).map((item) => ({
          id: item.RecruitmentId, // for React key and modal
          recruitmentId: String(item.RecruitmentId),
          recruitmentDate: item.RecruitmentDate ? item.RecruitmentDate.substring(0, 10) : '',
          firstName: item.FirstName,
          middleName: item.MiddleName,
          lastName: item.LastName,
          phone: item.Phone,
          email: item.Email,
<<<<<<< HEAD
          position: item.Position ?? (item as any).position ?? '',
=======
          position: item.Position ?? (item as any).position ?? '',
>>>>>>> e005fba (Initial commit from workspace)
          status: item.Status,
          notes: item.Notes,
          createdAt: item.CreatedAt,
          // add other fields as needed
        }));
        setRequests(mapped);
      } catch (err: unknown) {
        if (err instanceof Error) {
          setError(err.message);
        } else {
          setError('Unknown error');
        }
      } finally {
        setLoading(false);
      }
    };
    fetchRequests();
  }, [modalOpen]);

  // RecruitmentID is now generated by the backend

  // Helper to generate new RecruitmentId
  const generateRecruitmentId = async (): Promise<string> => {
    // Fetch the latest RecruitmentId from the backend
    const url = `${import.meta.env.VITE_API_BASE_URL}/recruitment?limit=1&sort=desc`;
    try {
      const res = await fetch(url, {
        headers: { 'x-api-key': import.meta.env.VITE_API_KEY },
      });
      if (!res.ok) throw new Error('Failed to fetch latest RecruitmentId');
      const data = await res.json();
      let lastId = 'GS-00000000-00000';
      if (Array.isArray(data) && data.length > 0 && data[0].RecruitmentId) {
        lastId = String(data[0].RecruitmentId);
      }
      // Extract last 5 digits and increment
      const today = new Date();
      const yyyy = today.getFullYear();
      const mm = String(today.getMonth() + 1).padStart(2, '0');
      const dd = String(today.getDate()).padStart(2, '0');
      const dateStr = `${yyyy}${mm}${dd}`;
      let lastNum = 0;
      const match = lastId.match(/GS-\d{8}-(\d{5})$/);
      if (match) {
        lastNum = parseInt(match[1], 10);
      }
      const newNum = (lastNum + 1).toString().padStart(5, '0');
      return `GS-${dateStr}-${newNum}`;
    } catch {
      // fallback if fetch fails
      const today = new Date();
      const yyyy = today.getFullYear();
      const mm = String(today.getMonth() + 1).padStart(2, '0');
      const dd = String(today.getDate()).padStart(2, '0');
      return `GS-${yyyy}${mm}${dd}-00001`;
    }
  };

  const handleAdd = async () => {
    const newRecruitmentId = await generateRecruitmentId();
    setSelectedRequest({ id: 0, position: '', status: '', recruitmentId: newRecruitmentId, recruitmentDate: new Date().toISOString().substring(0, 10), firstName: '', middleName: '', lastName: '', phone: '', email: '', resumeAttachment: null });
    setModalOpen(true);
  };
  const handleEdit = (req: RecruitmentRequest) => {
    setSelectedRequest(req);
    setModalOpen(true);
  };
  const handleCloseModal = () => {
    setModalOpen(false);
    setSelectedRequest(null);
  };
  const handleSave = async (req: RecruitmentRequest, attachments: File[]) => {
    setLoading(true);
    setError(null);
    try {
      let response;
      if (attachments && attachments.length > 0) {
        alert('File upload is not supported by the backend. Please remove the attachment.');
        setLoading(false);
        return;
      }
      const payload = { ...req };
      // If id is 0 or falsy, treat as new (POST), else update (PUT)
      if (!req.id) {
        if (!payload.recruitmentId) {
          payload.recruitmentId = await generateRecruitmentId();
        }
        response = await fetch(`${import.meta.env.VITE_API_BASE_URL}/recruitment`, {
          method: 'POST',
          headers: {
            'x-api-key': import.meta.env.VITE_API_KEY,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(payload),
        });
        if (response.ok) {
          const data = await response.json();
          req.recruitmentId = data.recruitmentId || payload.recruitmentId;
        }
      } else {
        response = await fetch(`${import.meta.env.VITE_API_BASE_URL}/recruitment/${req.recruitmentId}`, {
          method: 'PUT',
          headers: {
            'x-api-key': import.meta.env.VITE_API_KEY,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(payload),
        });
      }
      if (!response.ok) throw new Error('Failed to save recruitment request');
      setStatusModal({ open: true, success: true, message: !req.id ? 'Recruitment registered successfully!' : 'Recruitment updated successfully!' });
      setModalOpen(false);
      setSelectedRequest(null);
    } catch (err: unknown) {
      setStatusModal({ open: true, success: false, message: err instanceof Error ? err.message : 'Unknown error' });
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  // Sidebar navigation


  const handleLogout = () => {
    localStorage.removeItem('hrapp.authenticated');
    window.location.hash = '#/login';
  };

  return (
    <div className="recruitment-bg">
      <TopBar theme={theme} setTheme={setTheme} handleLogout={handleLogout} />
      {/* Content Row: Sidebar + Main Content */}
      <div className="recruitment-content-row">
        {/* Sidebar */}
        <Sidebar />
        {/* Main Content */}
        <main className="recruitment-main">
          <h2 className="recruitment-title">Recruitment</h2>
          <div className="recruitment-header-row">
            <button className="sidebar-btn recruitment-btn" onClick={() => window.location.hash = '#/'}>Back to Dashboard</button>
            <button className="sidebar-btn recruitment-btn" onClick={handleAdd}>Register Applicant</button>
          </div>
          <div className="recruitment-table-card">
            <h3 className="recruitment-table-title">Recruitment Requests</h3>
            <div className="recruitment-table-wrapper">
              {loading && <p>Loading recruitment requests...</p>}
              {error && <p className="recruitment-error">Error: {error}</p>}
              {!loading && !error && (
                <table className="recruitment-table">
                  <thead>
                    <tr>
                      <th>Recruitment ID</th>
                      <th>Recruitment Date</th>
                      <th>Full Name</th>
                      <th>Phone</th>
                      <th>Email</th>
                      <th>Position</th>
                      <th>Status</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {requests.length === 0 ? (
                      <tr><td colSpan={8} className="recruitment-table-empty">No recruitment requests found.</td></tr>
                    ) : (
                      requests.map(req => (
                        <tr key={req.recruitmentId || req.id}>
                          <td>{req.recruitmentId}</td>
                          <td>{req.recruitmentDate}</td>
                          <td>{`${req.lastName || ''}${req.lastName && req.firstName ? ', ' : ''}${req.firstName || ''}${req.middleName ? ' ' + req.middleName : ''}`}</td>
                          <td>{req.phone}</td>
                          <td>{req.email}</td>
                          <td>{req.position}</td>
                          <td>{req.status}</td>
                          <td><button className="sidebar-btn modal-action-save" onClick={() => handleEdit(req)}>Edit</button></td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              )}
              {loading && <Loading message="Loading recruitment requests..." />}
            </div>
          </div>
          <RecruitmentModal
            request={selectedRequest}
            open={modalOpen}
            onClose={handleCloseModal}
            onSave={(req: RecruitmentRequest) => handleSave(req, [])}
            onDelete={async (req: RecruitmentRequest) => {
              if (!req.id) return;
              if (!window.confirm('Are you sure you want to delete this recruitment request?')) return;
              setLoading(true);
              setError(null);
              try {
                const response = await fetch(`${import.meta.env.VITE_API_BASE_URL}/recruitment/${req.id}`, {
                  method: 'DELETE',
                  headers: { 'x-api-key': import.meta.env.VITE_API_KEY },
                });
                if (!response.ok) throw new Error('Failed to delete recruitment request');
                setStatusModal({ open: true, success: true, message: 'Recruitment deleted successfully!' });
                setModalOpen(false);
                setSelectedRequest(null);
                setRequests(prev => prev.filter(r => r.id !== req.id));
              } catch (err: unknown) {
                setStatusModal({ open: true, success: false, message: err instanceof Error ? err.message : 'Unknown error' });
                setError(err instanceof Error ? err.message : 'Unknown error');
              } finally {
                setLoading(false);
              }
            }}
          />

        <StatusModal
          open={statusModal.open}
          success={statusModal.success}
          message={statusModal.message}
          onClose={() => setStatusModal({ ...statusModal, open: false })}
        />
        </main>
      </div>
    </div>
  );

};

export default Recruitment;